executable	= protest_KeysPdfRead5_sdiat.sh
output		= output/$(file).out
error		= error/$(file).err
log		= log/$(file).log
MY.WantOS = "el7"

initialdir = /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5

+JobFlavour = "testmatch"

file=R0_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R1_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R2_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R3_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R4_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R5_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R6_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R7_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R8_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R9_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R10_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R11_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R12_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R13_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R14_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R15_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R16_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R17_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R18_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R19_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R20_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R21_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R22_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R23_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R24_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R25_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R26_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R27_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R28_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R29_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R30_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R31_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R32_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R33_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R34_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)

file=R35_q10_amsd68n_KeysPdfRead_AfterShift_NVar5_xy2_layer2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TempletFit/amsd68n_B1130_q10_NVar5/submit/arg/$(file)
