executable	= protest_cKeysPdf5.sh
output		= output/$(file).out
error		= error/$(file).err
log		= log/$(file).log
MY.WantOS = "el7"

initialdir = /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2

+JobFlavour = "testmatch"

file=R0_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R1_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R2_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R3_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R4_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R5_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R6_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R7_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R8_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R9_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R10_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R11_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R12_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R13_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R14_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R15_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R16_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R17_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R18_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R19_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R20_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R21_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)

file=R22_amsdn_runplotKeysPdf_T2
queue arguments from /afs/cern.ch/work/j/jzhang2/AMS/analisiP8/TemplateFit/L2ShiftWithL1_OddCh/amsdn_B1130_runplotKeysPdf_T2/submit/arg/$(file)
