#!/bin/tcsh

#### need to be set
#setenv ROOTSYS /afs/cern.ch/exp/ams/Offline/root/Linux/527.icc64
####

if ( ! $?ROOTSYS ) then
  setenv ROOTSYS /afs/cern.ch/exp/ams/Offline/root/Linux/527.icc64
endif 
if ( ! $?Offline ) then
  setenv Offline /afs/cern.ch/ams/Offline
endif 

source $Offline/vdev/install/amsvar

if ( ! $?AMSDEPLIB ) then
  setenv AMSDEPLIB /afs/cern.ch/ams/local2/opt
endif
if ( "$1" != "" )  then
  setenv AMSWD $1
endif
if ( "$2" != "" )  then
    setenv ADDBUILDNO 1
else
    unsetenv ADDBUILDNO
endif

unsetenv PGTRACK
unsetenv AMSLIB 
unsetenv  CERNDIR    
unsetenv  CERNICC     
unsetenv  CERNSRCDIR  

unsetenv SLC6system
setenv CXXVERS `g++ -dumpversion | tr -d "."`

setenv PREFIX $Offline/vdev/install
setenv TESTFLAG 
unsetenv G4AMS
unsetenv MARCH
setenv ECALBDT 1

unsetenv MARCH
source amsvar.gcc64
source g4i.gcc64

# Multi-threaded built (2 openMP threads)
setenv AMSPARALLEL 1
# Create corba object only once, instead of doing that on 
# each transaction, to avoid memory leaks, on DEVELOPMENT!
setenv NARROW_ONCE 1
# Build dynamically for CC7, because static link 
# brings segmentation crash to glibc library
if ( "$CXXVERS" >= "485" ) then
  setenv AMSDYNSERVER 1
endif
# If defined, adds 'long uid' to dst descriptor
setenv UID2DST 1
gmake server

unsetenv MARCH
source amsvar.gcc32
source g4i.gcc32
#gmake server

# Mew schema for the BDB of production server.
# For production release B900_patches must not be used 
setenv BDB_VERSION 1.0

make MARCH=linuxx8664gcc -C../prodtools -j
