[sync_cvmfs]
folders =
    # __sync_offline
    CERN,
    geant4.10.01.p01-ams,
    vdev,
    lib,
    AMSsoft,
    # __sync_offline_datadir
    AMSDataDir/v5.00,
    AMSDataDir/SlowControlDir,
    AMSDataDir/DataManagement,
    AMSDataDir/altec,
    AMSDataDir/isssa,
    AMSDataDir/ExtAlig,

folders_change_time =
    # __sync_offline_datadir_database
    AMSDataDir/DataBase/TRDAlignmentPlane,
    AMSDataDir/DataBase/TRDAlignmentGlobal,
    AMSDataDir/DataBase/TRDCalibration,
    AMSDataDir/DataBase/TofCAlignIon3,
    AMSDataDir/DataBase/DynAlignmentV5T090115PM5,
    AMSDataDir/DataBase/TrackerCals,
    AMSDataDir/DataBase/TRDPedestals,
    AMSDataDir/DataBase/TRDSigmas,
    AMSDataDir/DataBase/Tofpeds,
    AMSDataDir/DataBase/Antipeds,
    AMSDataDir/DataBase/RichPMTChannelCalibration,
    AMSDataDir/DataBase/Ecalpeds,
    AMSDataDir/DataBase/Map

